# Uncomment the next line to define a global platform for your project
 platform :ios, '11.2'

target 'CG2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CG2

  pod 'XLPagerTabStrip'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
end
